repos:
-   repo: https://github.com/PyCQA/bandit
    rev: '1.7.8'
    hooks:
    -   id: bandit
-   repo: https://github.com/ambv/black
    rev: 24.4.2
    hooks:
    - id: black
-   repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
    -   id: isort
        args: ["--profile", "black"]
-   repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
    - id: flake8
